name: Process data and deploy static page
on:
  push:
    paths:
    - 'src/**'
    - '.github/**'
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/usr/src/famousworld -w /usr/src/famousworld \
        python:3.8 /bin/bash -c "pip3 install -r requirements.txt && python3 src/process.py"
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'mbien-public'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        SOURCE_DIR: 'data'
        DEST_DIR: 'com-480'